
services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis


  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: shark
    ports:
      - "5432:5432"
      - "51000:51000"

  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
