# Generated by Django 4.1.6 on 2023-02-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_status', models.CharField(max_length=20)),
                ('protocols', models.CharField(max_length=20)),
                ('open_ports', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('os_detection', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=20)),
                ('os_family', models.CharField(max_length=20)),
                ('osgen', models.CharField(max_length=20)),
            ],
        ),
    ]
