# Generated by Django 4.2.5 on 2023-11-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaninfo',
            name='is_execution_complete',
            field=models.BooleanField(default=False),
        ),
    ]
