# Generated by Django 4.2.1 on 2023-09-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentscan',
            name='state_scan',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
