# Generated by Django 4.1.6 on 2023-03-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.CharField(max_length=20)),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.dataserver')),
            ],
        ),
    ]
