# Generated by Django 4.2.5 on 2024-03-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaninfo',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='osfamily',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='osgen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scaninfo',
            name='vendor',
            field=models.CharField(max_length=40),
        ),
    ]
