# Generated by Django 4.2.1 on 2023-09-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_scaninfo_data_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('mask', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=20)),
            ],
        ),
    ]
