# Generated by Django 4.2.1 on 2023-09-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_segmentscan_state_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_scan', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='server.clientbd')),
            ],
        ),
    ]
