# Generated by Django 4.2.5 on 2024-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_scaninfo_full_name_alter_scaninfo_osfamily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataserver',
            name='port',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
