# Generated by Django 4.1.6 on 2023-03-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_clientbd_id_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbd',
            name='id_client',
        ),
        migrations.AddField(
            model_name='dataserver',
            name='id_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.clientbd'),
        ),
    ]
