# Generated by Django 4.1.6 on 2023-03-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_remove_clientbd_id_client_dataserver_id_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataserver',
            old_name='id_client',
            new_name='client',
        ),
    ]
