# Generated by Django 4.1.6 on 2023-03-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_id_client_dataserver_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataserver',
            name='tag',
            field=models.BooleanField(default=False),
        ),
    ]
