# Generated by Django 4.1.6 on 2023-03-07 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_dataserver_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataserver',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.clientbd'),
        ),
    ]
