# Generated by Django 4.1.6 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_dataserver_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataserver',
            name='tag',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
