# Generated by Django 4.1.6 on 2023-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_dataserver_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataserver',
            name='tag',
            field=models.CharField(default='false', editable=False, max_length=10),
        ),
    ]
