# Generated by Django 4.1.6 on 2023-03-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_dataserver_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataserver',
            name='tag',
            field=models.BooleanField(default=False),
        ),
    ]
