# Generated by Django 4.2.4 on 2023-09-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_alter_dataserver_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaninfo',
            name='os_detection',
        ),
        migrations.RemoveField(
            model_name='scaninfo',
            name='os_family',
        ),
        migrations.RemoveField(
            model_name='scaninfo',
            name='osgen',
        ),
        migrations.RemoveField(
            model_name='scaninfo',
            name='vendor',
        ),
    ]
