# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nprot.proto\"&\n\nDataServer\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"\x1b\n\nDataClient\x12\r\n\x05state\x18\x01 \x01(\t2)\n\x03RPC\x12\"\n\x04scan\x12\x0b.DataClient\x1a\x0b.DataServer\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATASERVER._serialized_start=14
  _DATASERVER._serialized_end=52
  _DATACLIENT._serialized_start=54
  _DATACLIENT._serialized_end=81
  _RPC._serialized_start=83
  _RPC._serialized_end=124
# @@protoc_insertion_point(module_scope)
